name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  webdriverio:
    name: ${{ matrix.browser }}
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 20
      - run: yarn install
      - uses: browser-actions/setup-firefox@latest
        if: matrix.browser == 'firefox'
      - run: yarn run test:${{ matrix.browser }}